### PR TITLE
Remove webpack in favor of TS environment

### PR DESCRIPTION
**Pull request by andersevenrud**
* Removed webpack setup entirely
* Now using ts-node-dev as development runtime
* Added a custom entrypoint for api
* NODE_ENV is now "development" by default
* No more bundles, which means that you get real stack traces

### CODE REVIEW

**Comment by andersevenrud** [comment]
Updated with new commit message...

**Review by RossComputerGuy — APPROVED** [review]
I didn't know you didn't need webpack for TS

**Comment by andersevenrud** [comment]
TS comes with batteries included :)

**Comment by andersevenrud** [comment]
Some advantages of these changes:

* Almost instant startup time
* Reduced dependency count
* Creates node native code, not experimental ESM
* Better stack traces

**Comment by andersevenrud** [comment]
And also, since it's using the ts-dev environment and now development by default it will behave as nodemon does.

**Pull request merged**
