### PR TITLE
Add E2E tests for user registration

### PR DESCRIPTION
**Pull request by andersevenrud**
These commits adds a full test suite ready to go and includes tests for user registration endpoint.

Also this is a **very good** starting point for TDD :nerd_face: 

Just with this small update [and my other PRs] you get pretty good coverage:

Code-coverage-report-for-All-files (1)

### CODE REVIEW

**Review by RossComputerGuy — COMMENTED** [review]
Why is `NODE_ENV` removed?

**Comment by andersevenrud** [comment]
Look at the complete commit message.

**Comment by RossComputerGuy** [comment]
> This overrides Jest env variable, causing some invalid states in tests

I don't think its the best solution to remove the env var. Is there another way to not have invalid states in the test with `NODE_ENV` set?

**Comment by andersevenrud** [comment]
But you don't need to set NODE_ENV. This is automatic. It should **only** be set in a production environment.

The only cases where you need to check the NODE_ENV if it's in either "production" or "test" anyways.

**Comment by andersevenrud** [comment]
> Is there another way to not have invalid states in the test with NODE_ENV set?

Yeah, to set the NODE_ENV to `test` manually. But that's not something you wanna do, because test is outside normal runtime.

And prefixing commands don't make sense.

**Comment by andersevenrud** [comment]
A better way to think of this maybe:

The solution should default to the runtime defaults. Which is an unset `NODE_ENV` and let whatever tool/runtime is used manage this (ex: jest, which sets it to `test`) and only set it to `production` in either dotenv or docker-compose (I recommend separate compose files as you might want dev only services like database admin UI)  when it goes onto a production server.

**Comment by RossComputerGuy** [comment]
Yeah, it would be better to have a different compose file for development/testing and production.

**Comment by andersevenrud** [comment]
If you want to use Kubernetes or Docker Swarm mode you pretty much have to, because the dotenv will not work; all variables needs to be baked into the compose file.

**Comment by andersevenrud** [comment]
FYI: You can test this yourself with `docker-compose exec server_api npx jest --coverage --verbose` .

You'll get the results in the CLI and the HTML rendered ones in `packages/api/coverage/lcov-report`.

**Comment by RossComputerGuy** [comment]
There's a conflict that needs to be resolved first before this can be merged.

**Comment by andersevenrud** [comment]
Ah, you merged it before I pushed one final change. No worries, I'll cherry-pick that in a new PR :)

**Comment by RossComputerGuy** [comment]
Oh, I didn't know you weren't done lol

**Comment by andersevenrud** [comment]
It was actually caught just in time. Like 5 seconds :joy: 

https://github.com/ExpidusOS/website/commit/2474872ae14cf9cff892f5e0a61345414f692fa4

**Comment by RossComputerGuy** [comment]
Oh, so that's why I got a bit of an error right as it was merging.

**Pull request merged**
