### PR TITLE
Base refactor

### PR DESCRIPTION
**Pull request by andersevenrud**
* Separated services
* Split out winston into a provisional
* Split out database initialization into static members on models
* Split out express application
* Added exception handling
* Added an alternate dependency injection
* Added validation as a middleware
* Use async sugar over promises

### CODE REVIEW

**Comment by andersevenrud** [comment]
Note, I havent fired this up yet. I just changed things up like I had in mind to give you a better idea before going forward.

**Comment by RossComputerGuy** [comment]
```
server_api_1   | ERROR in /usr/src/api/src/oauth.ts
server_api_1   | 5:24-46
server_api_1   | [tsl] ERROR in /usr/src/api/src/oauth.ts(5,25)
server_api_1   |       TS2307: Cannot find module './models/accesstoken' or its corresponding type declarations.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/oauth.ts
server_api_1   | 6:19-36
server_api_1   | [tsl] ERROR in /usr/src/api/src/oauth.ts(6,20)
server_api_1   |       TS2307: Cannot find module './models/client' or its corresponding type declarations.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/oauth.ts
server_api_1   | 7:17-32
server_api_1   | [tsl] ERROR in /usr/src/api/src/oauth.ts(7,18)
server_api_1   |       TS2307: Cannot find module './models/user' or its corresponding type declarations.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/server.ts
server_api_1   | ./src/server.ts 18:18-21
server_api_1   | [tsl] ERROR in /usr/src/api/src/server.ts(18,19)
server_api_1   |       TS2304: Cannot find name 'app'.
server_api_1   |  @ ./src/index.ts 1:0-30 2:19-25
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/app.ts
server_api_1   | 8:9-18
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/app.ts(8,10)
server_api_1   |       TS2459: Module '"./exceptions"' declares 'HttpError' locally, but it is not exported.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/app.ts
server_api_1   | 34:9-12
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/app.ts(34,10)
server_api_1   |       TS7006: Parameter 'err' implicitly has an 'any' type.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/app.ts
server_api_1   | 34:14-17
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/app.ts(34,15)
server_api_1   |       TS7006: Parameter 'req' implicitly has an 'any' type.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/app.ts
server_api_1   | 34:19-22
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/app.ts(34,20)
server_api_1   |       TS7006: Parameter 'res' implicitly has an 'any' type.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/app.ts
server_api_1   | 34:24-28
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/app.ts(34,25)
server_api_1   |       TS7006: Parameter 'next' implicitly has an 'any' type.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/exceptions.ts
server_api_1   | 9:9-24
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/exceptions.ts(9,10)
server_api_1   |       TS2304: Cannot find name 'ValidatorResult'.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/exceptions.ts
server_api_1   | 32:9-24
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/exceptions.ts(32,10)
server_api_1   |       TS2304: Cannot find name 'ValidatorResult'.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/exceptions.ts
server_api_1   | 34:21-36
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/exceptions.ts(34,22)
server_api_1   |       TS2304: Cannot find name 'ValidatorResult'.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/controllers/user.ts
server_api_1   | 5:9-20
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/controllers/user.ts(5,10)
server_api_1   |       TS2305: Module '"../exceptions"' has no exported member 'BaseMessage'.
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/controllers/user.ts
server_api_1   | 5:22-40
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/controllers/user.ts(5,23)
server_api_1   |       TS2724: '"../exceptions"' has no exported member named 'HttpValidatorError'. Did you mean 'HttpValidationError'?
server_api_1   |
server_api_1   | ERROR in /usr/src/api/src/http/controllers/user.ts
server_api_1   | 24:34-41
server_api_1   | [tsl] ERROR in /usr/src/api/src/http/controllers/user.ts(24,35)
server_api_1   |       TS2339: Property 'results' does not exist on type 'ValidatorResult'.
```
Yeah, booting it up shows a lot of errors.

**Comment by andersevenrud** [comment]
Yes. There's no point in doing that yet. There's a few missing things here and there. The idea here was to get some feedback :)

**Comment by RossComputerGuy** [comment]
Ah, it looks good so far.

**Comment by andersevenrud** [comment]
I forgot to add the summary that I sketched out... D'oh.

Changes:

* Separated services
* Split out winston into a provisional
* Split out database initialization into static members on models
* Split out express application
* Added exception handling
* Added an alternate dependency injection
* Use async sugar over promises

**Comment by andersevenrud** [comment]
> Ah, it looks good so far.

Does this mean that you might consider using these changes ? Because I don't wanna spend more time on this if you just wanted to get ideas and not actual code :nerd_face:

**Comment by RossComputerGuy** [comment]
I'd use them, seems easier to manage.

**Comment by andersevenrud** [comment]
Well, I completed what I had in mind for this specific PR... but now I'm getting #1 after setting up a fresh database :joy:

**Review by RossComputerGuy — APPROVED** [review]

**Comment by andersevenrud** [comment]
Disregard my previous comment. This has been resolved.

I guess this is ready then. Works as expected on my end.

**Pull request merged**
